---
license_codes:
disks:
motd:
dns:
ntp:
snmp:
aggrs:
ports:
ifgrps:
vlans:
bcasts:
inters:
cluster:
cluster_name: temp
autonegotiate: true
flowcontrol: none
distribution_function: ip
ifgrp_mode: multimode_lacp
bcast_ipspace: Default
mtu: 9000
